name: Extension Validation

on:
  pull_request:
  push:
    branches:
      - main
      - 5.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-extensions:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          
      - name: Run repository content validation
        run: |
          python scripts/check_repository_content.py \
            --output-format markdown > repository-content-report.md || true

      - name: Get changed files
        run: |
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed_files.txt

      - name: Run extension validation
        run: |
          python scripts/check_description_files.py \
            --report-file extension-validation-report.md \
            --extension-descriptions-folder . \
            $(< changed_files.txt) || true
            
      - name: Combine validation reports
        if: always()
        run: |
          echo "# Combined Validation Report" > validation-report.md
          echo "" >> validation-report.md
          echo "## Repository content Validation" >> validation-report.md
          echo "" >> validation-report.md
          if [ -f repository-content-report.md ]; then
            tail -n +2 repository-content-report.md >> validation-report.md
          else
            echo "❌ Repository content validation report not generated" >> validation-report.md
          fi
          echo "" >> validation-report.md
          echo "---" >> validation-report.md
          echo "" >> validation-report.md
          echo "## Extension Description Validation" >> validation-report.md
          echo "" >> validation-report.md
          if [ -f extension-validation-report.md ]; then
            tail -n +2 extension-validation-report.md >> validation-report.md
          else
            echo "❌ Extension validation report not generated" >> validation-report.md
          fi
            
      - name: Display validation summary
        if: always()
        run: |
          echo "## Validation Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f validation-report.md ]; then
            cat validation-report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Validation report not generated" >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: Upload validation reports
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: validation-reports
          path: |
            validation-report.md
            repository-content-report.md
            extension-validation-report.md
          retention-days: 30
          
      - name: Comment PR with report
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.1
        with:
          script: |
            const fs = require('fs');
            
            // Check if validation report exists
            if (!fs.existsSync('validation-report.md')) {
              console.log('Validation report not found');
              return;
            }
            
            const report = fs.readFileSync('validation-report.md', 'utf8');
            
            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Combined Validation Report')
            );
            
            const commentBody = `<!-- extension-validation-report -->
            ${report}

            ---
            *This report was automatically generated by the Extension Validation workflow.*`;
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }
